### PR TITLE
fix: IMAP FETCH field mapping and partial column validation

### LINKED ISSUE #202: IMAP: FETCH returns no data due to MailModel validation and field mapping bugs
## Summary

IMAP FETCH commands return `OK FETCH completed` with no data for any mailbox. Two root causes:

### Bug 1: MailModel validation fails on partial SELECT

`getMailsByRange()` in `mails.ts` creates `new MailModel(row)` for each result row. When IMAP FETCH requests specific fields (e.g., only FLAGS), the SQL query only selects those columns. But `MailModel` constructor validates ALL 29 fields, throwing `ModelValidationError` because unrequested fields are `undefined`.

The error is caught by `getMailsByRange`'s catch block, which returns an empty Map. FETCH then processes the empty result and responds `OK FETCH completed` with no untagged `* n FETCH` responses.

**Stack trace:**
```
ModelValidationError: MailModel validation failed:
mail_id: undefined (undefined)
...
  at new Model (src/server/lib/postgres/models/base.ts:67:34)
  at new MailModel (src/server/lib/postgres/models/mail.ts:202:5)
  at src/server/lib/postgres/repositories/mails.ts:552:30
```

### Bug 2: IMAP field names not mapped to SQL column names

`mapFieldName()` in `store.ts` only maps `messageId` → `message_id` and `uid` → `uid_domain, uid_account`. When ENVELOPE is requested, `getRequestedFields()` adds `from`, `to`, `cc`, `bcc` — which are MailType property names, not SQL column names.

- `from` is a SQL reserved word → causes `syntax error at or near "from"`
- Even if quoted, the actual column names are `from_address`, `to_address`, `cc_address`, `bcc_address`
- Similarly `replyTo` should map to `reply_to_address, reply_to_text`

**SQL error:**
```
error: syntax error at or near "from"
severity: "ERROR"
position: "82"
code: "42601"
```

## Impact

- ALL IMAP FETCH commands fail silently — no email data is ever returned
- This breaks every IMAP client (Apple Mail, Thunderbird, etc.)
- EXISTS count is correct but messages cannot be retrieved

## Reproduction

```bash
(echo -e 'a001 LOGIN admin inbox\r\n'; sleep 2; echo -e 'a002 SELECT INBOX\r\n'; sleep 5; echo -e 'a003 FETCH 1 (FLAGS)\r\n'; sleep 3; echo -e 'a004 LOGOUT\r\n'; sleep 1) | nc -w15 127.0.0.1 143
```

Expected: `* 1 FETCH (FLAGS (\Seen))` before OK
Actual: `a003 OK FETCH completed` with no data

## Root Cause Files

- `src/server/lib/imap/store.ts` — `mapFieldName()` incomplete, `getMessages()` uses MailModel for partial data
- `src/server/lib/postgres/repositories/mails.ts` — `getMailsByRange()` creates MailModel from partial rows
- `src/server/lib/imap/session.ts` — `getRequestedFields()` uses MailType field names

## Proposed Fix

1. **Add field mappings** to `mapFieldName()`:
   - `from` → `from_address, from_text`
   - `to` → `to_address, to_text`
   - `cc` → `cc_address, cc_text`
   - `bcc` → `bcc_address, bcc_text`
   - `replyTo` → `reply_to_address, reply_to_text`
   - `attachments` → `attachments`
   - Also always include `mail_id` (used as Map key)

2. **Don't use MailModel for partial results** — either:
   - Always SELECT * (simpler, slightly less efficient), or
   - Return raw rows from `getMailsByRange` and map in store, or
   - Make MailModel accept partial data

Option A (always SELECT *) is simplest and safest since the IMAP fetch limit is already capped at 50 messages.

### PR DESCRIPTION
**Pull request by moltboie**
## Summary

Fixes two bugs that prevented IMAP FETCH from returning any message data. Closes #202.

### Bug 1: Field name mapping incomplete
`mapFieldName()` only mapped `messageId` and `uid`, but not `from`, `to`, `cc`, `bcc`, or `replyTo` to their SQL column names. Since `from` is a SQL reserved word, any ENVELOPE fetch caused a SQL syntax error. The actual database columns are `from_address`/`from_text`, `to_address`/`to_text`, etc.

### Bug 2: MailModel validation on partial SELECT
`getMailsByRange()` passed a field list to the SQL query (e.g., only `uid_domain, read, saved, deleted, draft` for FLAGS), then created `new MailModel(row)` from the partial result. MailModel validates all 29 fields, throwing `ModelValidationError` for missing columns. The error was caught and returned as an empty Map, making FETCH return OK with no data.

### Fix
1. Added all field mappings to `mapFieldName()`: `from` → `from_address, from_text`, `to` → `to_address, to_text`, `cc` → `cc_address, cc_text`, `bcc` → `bcc_address, bcc_text`, `replyTo` → `reply_to_address, reply_to_text`
2. Always use `SELECT *` in `getMailsByRange()` — the IMAP fetch limit (50 messages) already constrains result size, so partial column selection was a premature optimization

### E2E Testing
Started dev server and tested with raw IMAP commands via `nc`:
- **LOGIN** ✅
- **SELECT INBOX** ✅ (4182 EXISTS)
- **FETCH 1 (FLAGS)** ✅ — now returns `* 1 FETCH (FLAGS (\Seen))`
- **FETCH 1:3 (FLAGS ENVELOPE)** ✅ — returns 3 messages with full envelope data
- **UID FETCH 1 (FLAGS BODYSTRUCTURE)** ✅ — returns body structure
- **STORE 1 +FLAGS (\Flagged)** ✅ — adds flag
- **STORE 1 -FLAGS (\Flagged)** ✅ — removes flag
- **FETCH after STORE** ✅ — shows updated flags
- All 250 unit tests pass

### CODE REVIEW

File: src/server/lib/postgres/repositories/mails.ts [hunk 1]
```diff
@@ -490,15 +490,17 @@ export const getMailsByRange = async (
...
+  _fields: string[] = ["*"]
 ): Promise<Map<string, MailModel>> => {
   try {
     const uidField = account === null ? UID_DOMAIN : UID_ACCOUNT;
 
     let sql: string;
     let values: ParamValue[];
 
-    const fieldList = fields.includes("*") ? "*" : fields.join(", ");
+    // Always SELECT * to avoid MailModel validation errors with partial columns.
```
Comment (hoiekim) [inline src/server/lib/postgres/repositories/mails.ts]: That's not a proper fix. You should create a mechanism that does partial model validation. Field list should be validated too. Then you can do `new PartialMail(...)` or something like that.
